spring.application.name=product-service
server.port=8081
spring.datasource.url = jdbc:mysql://localhost:3306/shopease_product
spring.datasource.username = root
spring.datasource.password = Systems@2026

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql= true

spring.jpa.properties.hibernate.format_sql = true 